### PR TITLE
Feature/navigations test

### PR DESCRIPTION
**Pull request by Vasanth-BN**
CSR with Nested routing:
- Dynamic routing.
- Nested Routing.
- Test coverage.

### CODE REVIEW

**Comment by Vasanth-BN** [comment]
Screenshot (126)
Code coverage.

**Comment by aashikvilla** [comment]
Can you make brand dynamic as well -> {base-url}/[brand]/[model]

**Comment by Vasanth-BN** [comment]
> Can you make brand dynamic as well -> {base-url}/[brand]/[model]

**Comment by Vasanth-BN** [comment]
I have made brand dynamic and also changed it to {base-url}/[brand]/[model]
Screenshot (127)

**Comment by Vasanth-BN** [comment]
Added new features and raising new PR

**Pull request closed without merging**
